version: '3.7'
services:
  flask-app:
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  mysql:
    build: ./db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
      MYSQL_ROOT_PASSWORD: ${BENS_PASSWORD}
